### ISSUE TITLE
Kernel Threads

### ISSUE THREAD

**Issue by ppenna** [nanvix/nanvix#210]
**Description**

Currently, processes have a single thread of execution. Since we are targeting manycore platforms we should add multithreading to the system

Although several implementations are possible, IMHO kernel threads should be our primary objective because mainly because it will be easier to introduce later on multicore support.

**Roadmap**

- [x] Create a thread structure.
- [x] Move thread specific fields from the process structure to the thread structure.
- [x] Write kernel routines for allocating, initializing and terminating a thread.
- [x] Hack low-level context switching routines
- [x] Hack system calls to rely on the thread abstraction
